server {
    listen 80;
    listen [::]:80;
    server_name cloud-staging.smalldocs.org;

    access_log off;

    location /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name cloud-staging.smalldocs.org;

    ssl_certificate /etc/letsencrypt/live/cloud-staging.smalldocs.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud-staging.smalldocs.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log off;
    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:3004;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_read_timeout 60s;
    }
}
