#!/usr/bin/env node
// Build script: read every Lucide icon from node_modules/lucide-static
// and emit public/sdocs-icons-data.js with their inner SVG content.
// The output is loaded on-demand by the slide renderer when the first
// `icon` shape is encountered on a page.
//
// Run: node scripts/build-icons.js
// Re-run after `npm install lucide-static@latest` to refresh icons.

const fs = require('fs');
const path = require('path');

const ICON_DIR = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const OUT = path.join(__dirname, '..', 'public', 'sdocs-icons-data.js');

const files = fs.readdirSync(ICON_DIR).filter(f => f.endsWith('.svg'));

const entries = [];
let totalBytes = 0;

for (const file of files) {
  const name = file.replace(/\.svg$/, '');
  const raw = fs.readFileSync(path.join(ICON_DIR, file), 'utf8');
  // Strip the <svg ...> wrapper (Lucide files have one root <svg>),
  // keeping only the inner element children.
  const match = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!match) {
    console.warn('skip (no <svg> tag): ' + file);
    continue;
  }
  // Collapse whitespace between elements so the bundle stays compact
  // but the SVG markup itself stays intact.
  const inner = match[1].replace(/>\s+</g, '><').trim();
  entries.push(JSON.stringify(name) + ':' + JSON.stringify(inner));
  totalBytes += inner.length;
}

const out = '// AUTO-GENERATED by scripts/build-icons.js. Do not edit by hand.\n' +
            '// Lucide icons (https://lucide.dev) - ' + entries.length + ' icons.\n' +
            '// Loaded lazily by sdocs-shape-render.js when the first `icon`\n' +
            '// shape is encountered.\n' +
            '(function () {\n' +
            '  window.SDocIcons = {\n' +
            '    ' + entries.join(',\n    ') + '\n' +
            '  };\n' +
            '  if (window.SDocIconsReady) window.SDocIconsReady();\n' +
            '})();\n';

fs.writeFileSync(OUT, out);
console.log('Wrote ' + OUT);
console.log('  ' + entries.length + ' icons, ' +
            (totalBytes / 1024).toFixed(1) + ' KB of path data, ' +
            (out.length / 1024).toFixed(1) + ' KB total file size');
